### ISSUE TITLE
latest release (in fork) for macOS has blurry font

### ISSUE THREAD

**Issue by SichangHe** [ahrm/sioyek#218] opened 2022-04-30 04:41 UTC
This refers to [the latest release](https://github.com/hexomancer/sioyek/releases/tag/v0.31.315) in [this fork](https://github.com/hexomancer/sioyek)

As soon as I opened it, I noticed that the PDF fonts are blurry. I can see the pixels of the characters while previously I saw smooth font.

I have already rolled back.

**Comment by ahrm** [comment] 2022-04-30 06:24
That's weird. Just to help me locate the issue, the latest build has this problem but the previous one ([this](https://github.com/hexomancer/sioyek/releases/tag/v0.31.314)) doesn't have this problem?
Also could you attach a screenshot of the issue?
And thanks for your feedback.

**Comment by SichangHe** [comment] 2022-04-30 06:34
The latest release that *does not have* this issue is [0.31.310](https://github.com/hexomancer/sioyek/releases/tag/v0.31.310).

I tried them from latest to oldest one by one.

**Comment by ahrm** [comment] 2022-04-30 13:15
I asked one of my friends who has a macbook to test the latest build but he was not able to reproduce the problem. The following information might help track down the problem:

* Which MacOS version are you using?
* On what hardware? (Is it a macbook? Is an external display connected?)
* Can you share your `prefs_user.config`? Maybe there is a config which is causing the issue.
* Does the issue persist on all PDF files or only some files (for example does it have the same issue on sioyek tutorial PDF?)

**Comment by SichangHe** [comment] 2022-04-30 14:09
```shell
$ neofetch
                    'c.          user_name@machine_name 
                 ,xNMM.          ---------------------------------------- 
               .OMMMMo           OS: macOS 12.0.1 21A559 arm64 
               OMMM0,            Host: MacBookPro17,1 
     .;loddo:' loolloddol;.      Kernel: 21.1.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 1 day, 6 hours, 47 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 167 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: fish 3.4.1 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 2560x1600 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: yabai 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: kitty 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   CPU: Apple M1 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   GPU: Apple M1 
    kMMMMMMMMMMMMMMMMMMMMMMd     Memory: 1463MiB / 8192MiB 
     ;KMMMMMMMWXXWMMMMMMMk.
       .cooc,.    .,coo:.                                
                                        
$ cat ~/.config/sioyek/prefs_user.config 
should_launch_new_instance 1                 
```
I did not try it on other PDFs.
I cannot reproduce it now neither using release 0.31.311 or 0.31.315, so I'll use the latest release now.

My guess is that either sioyek or some components of macOS failed to rerender after I did a zoom in, and after I switched some versions the system cleaned the cache or something and the problem got fixed by time and probability rather than the version difference.

Hard bug I guess. It is working now though.

**Comment by SichangHe** [comment] 2022-05-04 12:02
I experienced this again just now. This bug seems to persist.
Changed window size to one fourth and it was fixed. I wonder if it is partially because of the 4k external monitor.

**Comment by ahrm** [comment] 2022-05-04 12:12
Interesting. It could indeed be because of the external display. Here is my theory which you might be able to test:
When sioyek starts in the external display, then it is blurry but if it starts in Macbook display it is ok.

**Comment by SichangHe** [comment] 2022-05-04 13:04
I tried a few times.
1. the behavior could only happen when opening a new file
2. the behavior could only happen when the window size is 4k, if I manually resize the window size to slightly smaller, it could not be reproduced
so yes it does not happen in the MacBook display, and it resolves as soon as I resize the window
what I do currently is throwing it to my MacBook display and then back to the external display with the window manager (yabai)

**Comment by ahrm** [comment] 2022-05-04 13:07
Should probably be fixed in the latest build here:
https://github.com/hexomancer/sioyek/releases/tag/v0.31.317

**Comment by zhihuai1982** [comment] 2022-05-28 14:45
I have the same problem, the sioyek i use is  [the latest release](https://github.com/hexomancer/sioyek/releases/tag/v0.31.315)

when i open a new pdf i got blurry font like below

![Snipaste_2022-05-28_22-27-50](https://user-images.githubusercontent.com/36764265/170829840-912a875b-4b0a-4548-b371-37b2f20b2bd7.png)

after i change and restore the window size the font is clear again

![Snipaste_2022-05-28_22-28-08](https://user-images.githubusercontent.com/36764265/170829927-5eeff535-25e7-4b49-9d75-ab6d7b1206f8.png)

this only happens in my second monitor （I placed it vertically and its resolution is 1080*1920 ）
the display in my main monitor is totally fine (the resolution is 5120*2880)

when i maximize the window in my main monitor and copy-window-size-config, the output is 

single_main_window_size    2560 1440
single_main_window_move     0 0

same to the second monitor and the output is 

single_main_window_size    1080 1920
single_main_window_move     2560 -251

Hopefully I can provide some clues.

**Comment by ahrm** [comment] 2022-07-03 11:30
I think this issue is probably fixed in c446f7cf38830a7ac18ec5eb6ac2b30878fccd8b.

**Comment by SichangHe** [comment] 2022-07-03 11:49
Good new if you have the behavior normalized on your machine.
Unfortunately, I cannot test it anymore because I don't have that 4K screen anymore.
@zhihuai1982 Is the behavior normalized on your machine?

**Closed** 2022-07-14 10:10 UTC

**Comment by albert-ying** [comment] 2022-09-30 03:18
I think I have the similar issue in the recent releases --

The text is a little bit blurry. The main issue seems is that the sioyek somehow "think" my window is 2x wider, as when I run `fit_to_page_width`, it only shows left 50% of the page, and I can not move right. I will have to zoom out and move

<img width="1883" alt="image" src="https://user-images.githubusercontent.com/59846322/193182832-771814bc-f170-48ae-a2c1-6f6e6984238d.png">

**Comment by albert-ying** [comment] 2022-09-30 17:40
> Is this bug present in the previous releases in the fork?

Yes, the bug also presents up to [Release v0.31.386](https://github.com/hexomancer/sioyek/releases/tag/v0.31.386). I haven't tested on release earlier than that

> Also just to be sure: you have an external 4k monitor connected to a MacOS laptop?

Yes, but even when I move the window to the macOS screen, the behavior is the same.

**Comment by albert-ying** [comment] 2022-09-30 17:48
It is probably a different bug; It persist even after I disconnect the monitor and restart it -- so not related to the external monitor. I will open a new issue for it
