### ISSUE TITLE
[Feature request] Import annotations into current document for better cross PDF workflow.

### ISSUE THREAD

**Issue by Elaws** [ahrm/sioyek#495] opened 2022-11-20 14:53 UTC
# Usecase 

`embed_annotations` and `_embed_annotations` are really useful because they allow to use Sioyek annotations in other PDF readers (e.g. : Zotero PDF reader).

However, annotations made in other PDF readers, even if visible in Sioyek, can't be interacted (can't delete or search highlights, can't see bookmark content).

It would be really useful if we could import annotations from other PDF readers into Sioyek.

# Closer to a better cross PDF workflow

With a new `import_annotation` feature, someone that works with multiple PDF readers could simply use this simple workflow when working on a document : 

1. Load PDF in Sioyek.
2. `import_annotation`
3.  Add new annotations in Sioyek.
4. `_embed_annotations` 
5. Add annotations in another PDF reader.
6. Back to step 1.

**Comment by ahrm** [comment] 2022-11-21 19:22
Added a script to the new version of sioyek python extensions that imports the annotations from the PDF files.
Note that since PDF highlights do not store the highlighted text itself, we have to guess what the highlighted text is, and therefore, the imported highlights don't always match exactly with the original highlights.

**Comment by Elaws** [comment] 2022-11-21 21:57
This is great news, thanks a lot.

**Comment by Elaws** [comment] 2022-11-21 22:18
For the import script, should we use : 

`new_command import_annotations python -m sioyek.import_annotations "%{sioyek_path}" "%{local_database}" "%{shared_database}" "%{file_path}"`

**Comment by ahrm** [comment] 2022-11-21 22:34
Custom commands should always start with an underscore, so `import_annotations` should become `_import_annotations`.

**Comment by Elaws** [comment] 2022-11-21 23:28
I must be doing something wrong. In `prefs_user.config`, I added : 

`new_command _import_annotations python -m sioyek.import_annotations "%{sioyek_path}" "%{local_database}" "%{shared_database}" "%{file_path}"`

I installed the package with pip and do have `import_annotations.py` located somewhere.

**Comment by ahrm** [comment] 2022-11-22 09:44
Can't reproduce the issue, as shown in the video it works for the file you provided. Maybe you are running a wrong version of python that doesn't have the sioyek package? 

Try running this command (after replacing `%{}`s with the correct value) in a terminal and see if there are any errors.
```
python -m sioyek.import_annotations "%{sioyek_path}" "%{local_database}" "%{shared_database}" "%{file_path}"
```

https://user-images.githubusercontent.com/6392321/203280879-8fc7e1f2-9c05-4f13-90b3-0a6c03e3af80.mp4

**Comment by Elaws** [comment] 2022-11-22 14:20
Thank you, please find below the error log : 

> Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sioyek\import_annotations.py", line 17, in <module>
    document.import_annotations()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sioyek\sioyek.py", line 869, in import_annotations
    new_bookmarks = self.get_non_sioyek_bookmarks()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sioyek\sioyek.py", line 893, in get_non_sioyek_bookmarks
    bookmark_page = sioyek_bookmark.get_document_position().page
AttributeError: 'tuple' object has no attribute 'page'

**Comment by ahrm** [comment] 2022-11-22 17:12
Should be fixed in the latest version.

**Comment by Elaws** [comment] 2022-11-23 21:11
@ahrm : Thank you, the highlights are imported now. 

# Bug description

However, when using `_import_annotations` after you already used `_embed_annotations` leads to undesired behavior : 

1. First, I make some highlights within Sioyek. Everything is fine :

![1](https://user-images.githubusercontent.com/52013479/203645905-73930dd1-207c-42ee-921d-2a2aed9ba7f1.png)

2. Then, I use `_embed_annotations`. It works well. However, if you use `_import_annotations` again, it leads to undesired result : 

![2](https://user-images.githubusercontent.com/52013479/203646127-0362382c-b909-49f9-b0f4-395964ff20c4.png)

![3](https://user-images.githubusercontent.com/52013479/203646139-ddb0fdd0-feb0-41a4-80df-4eb012fa4251.png)

As you can see, lots of highlights are duplicated.

---

# Possible solution

I'm not sure what the best fix is, if one wants to regularly use chains of `_embed_annotations` and `_import_annotations`. The mix of external PDF highlights and Sioyek highlights is maybe problematic. 

Maybe `_import_highlights` should : 

1. Make sure that the highlight is not already in Sioyek highlights.
2. Delete external PDF highlights once they are properly imported.

If this gets fixed, we are now very close to a great workflow for better cross PDF compatibility.

**Comment by Elaws** [comment] 2022-11-24 13:06
Addendum : I have not checked yet if the same problem happens for bookmarks.

**Comment by ryanwwest** [comment] 2023-01-30 05:09
Not exactly the same thing, but satisfies a similar use case: I wonder if there would be any interesting in reading and writing annotations directly to Zotero 6's annotation storage. I.e., have a new extension that, rather than embed annotations in the file, just loads the annotations that Zotero has, displays them in Sioyek, and any annotations added by you in Sioyek aren't saved locally but are instead saved back to Zotero's annotation DB. 

Less complex in that it comes down to API translation of annotation data to/from data and no local storage of that, though I'm sure there is still a lot of complexity I'm unaware of.

**Comment by ahrm** [comment] 2023-01-30 09:59
Nice! If you have a git repository I could add its link [here](https://github.com/ahrm/sioyek-python-extensions#user-scripts).

**Comment by ahrm** [comment] 2024-01-26 10:25
We have added a built-in `import_annotations` command in the development branch.

**Closed by ahrm** 2024-01-26 10:25 UTC
