### ISSUE TITLE
[bug]Sioyek fails to open files if they contain chinese in the path or filename

### ISSUE THREAD

**Issue by wenbopeng** [ahrm/sioyek#428] opened 2022-09-21 02:28 UTC
Sioyek will not crash if you set `should_launch_new_instance 1` , and a new window is started when a new file is opened.
But if set to `should_launch_new_instance 0`, when there is Chinese in the file path like `D:\文档\Citavi\Citavi 6\Projects\基础知识\Citavi Attachments\file.pdf` or chinese in the filename like `D:\download\文件.pdf`, the current sioyek window will crash.

It should be pointed out that the above problem requires the mouse to double-click the file in the explorer. If you open recent files in the opened sioyek window, the above problem will not appear. (windows11 64-bit)

**Comment by ahrm** [comment] 2022-09-21 05:37
Which sioyek build are you using? This was an issue in 1.5 release but it should be fixed in the latest commits.

**Comment by wenbopeng** [comment] 2022-09-21 08:12
> Which sioyek build are you using? This was an issue in 1.5 release but it should be fixed in the latest commits.

https://github.com/hexomancer/sioyek/releases/tag/v0.31.391

**Comment by kiryph** [comment] 2022-10-16 15:00
@ahrm Any chance there will be a new release of sioyek (e.g. 1.5.1) in the near future containing latest fixes?

On my machine `$ git clone --recursive https://github.com/ahrm/sioyek` took 7m 16s which I would call slow.

**Comment by ahrm** [comment] 2022-10-16 15:07
There are newer experimental builds here: https://github.com/hexomancer/sioyek/releases/tag/v0.31.395

**Comment by kiryph** [comment] 2022-10-16 15:24
@ahrm Thanks for pointing me there. In the meanwhile, I have compiled sioyek myself. My steps under macOS 12.6:
```sh
# Install XCode & homebrew and then:
brew install qt@5 freeglut mesa harfbuzz

# ensure command qmake from qt@5 is used and compiler flags point to the correct qt version:
export PATH="/usr/local/opt/qt@5/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/qt@5/lib"
export CPPFLAGS="-I/usr/local/opt/qt@5/include"
export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"

git clone --recursive https://github.com/ahrm/sioyek # 7m 16s
cd sioyek
chmod +x build_mac.sh
export MAKE_PARALLEL=$(nproc) # set number of cores to speed up compilation
./build_mac.sh
```

**Comment by wenbopeng** [comment] 2022-10-18 11:47
> There are newer experimental builds here: https://github.com/hexomancer/sioyek/releases/tag/v0.31.395

Unfortunately, this issue still exists.

**Comment by ahrm** [comment] 2022-10-18 18:53
Can't reproduce the issue. Are you sure when double clicking on a file, windows is using the newer sioyek builds?

**Comment by MiuKaShi** [comment] 2022-11-01 10:03
Use AppImage version will cause such problem.  Change to build by myself, now everything seems to be fine.

**Closed** 2022-12-25 10:59 UTC
