### ISSUE TITLE
Sioyek doesn't work when placed in non-ascii paths

### ISSUE THREAD

**Issue by YijunYuan** [ahrm/sioyek#138] opened 2022-02-21 12:18 UTC
I use [sioyek](https://github.com/ahrm/sioyek/releases/download/v1.1.0/sioyek-release-windows.zip) on the Windows 11 Insider Preview (Dev channel). It just shows nothing:
![微信图片_20220221200731](https://user-images.githubusercontent.com/7012463/154952369-fe18e47d-79fc-42dc-8ebd-a7944fae734e.png)
The window doesn't seem to respond to keypress (nothing happens if I press `o`), although the page number changes if I use the mouse wheel.
I'm happy to provide the log file, if it exists.

Windows 11 version: 22557.1 (64bit)
Hardware Infomation: i7-8750H/GTX1060

**Comment by ahrm** [comment] 2022-02-21 12:22
Did you build sioyek yourself or are you using pre-built packages?

**Comment by ahrm** [comment] 2022-02-21 12:25
Did you unzip the file?

**Comment by YijunYuan** [comment] 2022-02-21 12:27
> Did you build sioyek yourself or are you using pre-built packages?

pre-built package [https://github.com/ahrm/sioyek/releases/download/v1.1.0/sioyek-release-windows.zip](https://github.com/ahrm/sioyek/releases/download/v1.1.0/sioyek-release-windows.zip)

**Comment by YijunYuan** [comment] 2022-02-21 12:27
> Did you unzip the file? (you should unzip the zip file before using sioyek)

Sure, I have unzipped it.

**Comment by ahrm** [comment] 2022-02-21 12:28
Maybe sioyek doesn't have permission to use the directory in which it is located? Maybe try moving it to another directory or launching it as administrator.

**Comment by YijunYuan** [comment] 2022-02-21 12:32
> Maybe sioyek doesn't have permission to use the directory in which it is located? Maybe try moving it to another directory or launching it as administrator.

As you can see from the screenshot, I unzipped it to my Desktop folder, so that shouldn't be a permission issue. Also, Run As Administrator doesn't work.

**Comment by ahrm** [comment] 2022-02-21 12:35
Hmmm this is strange. The issue you see is caused because for some reason `sioyek` can't access its shader and config files. But I don't know why in this case. Unfortunately I don't have a Window 11 machine so I can't test it myself.

Do you have the same issue with the potable build?

**Comment by YijunYuan** [comment] 2022-02-21 12:38
> Hmmm this is strange. The issue you see is caused because for some reason `sioyek` can't access its shader and config files. But I don't know why in this case. Unfortunately I don't have a Window 11 machine so I can't test it myself.
> 
> Do you have the same issue with the potable build?

OK, I know what's going wrong here. I moved `sioyek` to a pure ASCII path, and the program works. So **the program can't be placed in a folder with non-ASCII path**.

Maybe you should open a new Issue (after doing more tests...)

**Comment by ahrm** [comment] 2022-02-21 12:40
You are right, I was able to reproduce the issue. Let's just rename this issue.

**Comment by ahrm** [comment] 2022-02-21 16:41
Should be fixed in 3ccd75242936f1e100f6c981132516b613f32afd.

**Closed** 2022-02-22 08:30 UTC
