### ISSUE TITLE
Fonts turn fuzzy after edit_portal command 

### ISSUE THREAD

**Issue by alexzeitgeist** [ahrm/sioyek#247] opened 2022-05-23 18:13 UTC
Hi,

Everything looks great. But when I create a portal "p" and then do edit_portal "shift p", the page zooms out lightly and the fonts of the document are rendered all fuzzy, as if anti-aliasing got turned off. I tried everything to fix the issue: return to source location "backspace", zoom in and out, jump inside the document. The only remedy is to restart sioyek.    

sioyek: v1.3.0
os: ubuntu 22.04 xfce4
gpu: i915 tigerlake

**Comment by ahrm** [comment] 2022-05-23 18:17
Do you have multiple monitors? If so what are their resolutions?

**Comment by alexzeitgeist** [comment] 2022-05-24 12:10
Hi @ahrm,

Multiple monitors, correct:

eDP-1 connected 1920x1200+0+0 (normal left inverted right x axis y axis) 302mm x 189mm
DP-3-3 connected primary 2560x1440+1920+0 (normal left inverted right x axis y axis) 597mm x 336mm

Tragging the mouse in the helper window = without problem. The fonts are rendered perfectly.

**Comment by ahrm** [comment] 2022-05-24 12:37
I am  not able to reproduce the issue.
* Which monitor do you use for the main window and which one for the helper window?
* On which window does the font issue occur?

Also if you want to force linear texture filtering you can add the following to your `prefs_user.config`:

```
linear_filter 1
```

**Comment by alexzeitgeist** [comment] 2022-05-24 14:50
Hah, okay, first of all, using linear_filter 1 makes the issue go away.

But also when not using the linear_filter setting, the issue does not occur if sioyek runs on the primary (2560x1440) display. In other words,

2560x1440 (primary): portal "p" -> edit_port "shift p"  return "backspace" => font remains fine, not fuzzy
1920x1200 (secondary, notebook screen): portal "p" -> edit_port "shift p"  return "backspace" => font turns fuzzy.

Now, even when the font got fuzzy, if I move sioyek from the secondary screen to the primary screen, and maximize the window, the font turns from fuzzy to normal. Then, when I move sioyek back to the primary screen, the font remains fine. That is, until I repeat "p", "shift p", "backspace"...

**Comment by zhihuai1982** [comment] 2022-06-01 12:18
> 

I have the same problem.
my monitor arrangement are like this.

<img width="481" alt="Snipaste_2022-06-01_20-18-01" src="https://user-images.githubusercontent.com/36764265/171402644-479e926b-5e3b-4ef3-8156-bb660e8a70ee.png">

<img width="303" alt="Snipaste_2022-06-01_20-16-25" src="https://user-images.githubusercontent.com/36764265/171402660-ad8238a2-a970-41a5-9570-b547ce2afe2d.png">

**Comment by ahrm** [comment] 2022-07-03 11:32
Should be fixed in c446f7cf38830a7ac18ec5eb6ac2b30878fccd8b.

**Closed** 2022-07-14 10:10 UTC
