### ISSUE TITLE
Regression: scrollbar introduces scaling of rendered image

### ISSUE THREAD

**Issue by lennonhill** [ahrm/sioyek#413] opened 2022-09-08 12:12 UTC
https://github.com/ahrm/sioyek/commit/5f76ee681a18efe203aa0bcde250a6b10ede1672 causes a scaling of the rendered image, which reintroduces the artifacts eliminated by https://github.com/ahrm/sioyek/commit/8c2b4565b575c3c153d26da2492f5f396ca46621 .

**Comment by ahrm** [comment] 2022-09-08 12:17
Does it happen only when the scrollbar is active?

**Comment by ahrm** [comment] 2022-09-08 15:19
Which operating system are you using? And what is your Qt version?
Also can you see if this line is executed when you run `toggle_scrollbar` command?
https://github.com/ahrm/sioyek/blob/5f76ee681a18efe203aa0bcde250a6b10ede1672/pdf_viewer/document_view.cpp#L293

(it does run for me on windows, and also I am not able to reproduce the issue on windows).

**Comment by ahrm** [comment] 2022-09-08 16:46
Does toggling the scrollbar off/on fix the issue?

**Comment by ahrm** [comment] 2022-09-08 16:52
Is the issue fixed in 699e46581a854b8921ceae5c3712f34da279ff63?

**Closed** 2022-09-09 16:48 UTC
