### ISSUE TITLE
Not able to open multiple instances of Sioyek on Linux

### ISSUE THREAD

**Issue by SamuelMosesA** [ahrm/sioyek#69] opened 2021-09-28 04:15 UTC
I am not able to open multiple instances of Sioyek from the AppImage on Linux. I would like to have 2 files open on Sioyek instead of repeatedly using the open recent command to switch between them. Is there a way to achieve this at this moment? Will it be added in the future?

**Comment by Endle** [comment] 2021-09-28 05:44
This is a duplicate of https://github.com/ahrm/sioyek/issues/37

**Comment by Endle** [comment] 2021-09-28 05:50
Besides, @ahrm would you like to publish a new release? The git version will launch multiple instances by default (https://github.com/Endle/sioyek/commit/0da5939e89bb0aee92850c4e40599e57ad525ee0) , but this change is not included in the AppImage release

**Comment by Endle** [comment] 2021-09-28 05:51
Answer to @SamuelMosesA You can add `should_launch_new_instance				1` to your user's config

**Comment by SamuelMosesA** [comment] 2021-09-28 08:57
Thanks for the help. Keep up the great work on this application. It has been a real time saver for me.

**Closed** 2021-09-28 09:58 UTC
