### ISSUE TITLE
Chapters (and all links) in Epub not working

### ISSUE THREAD

**Issue by David-Else** [ahrm/sioyek#96] opened 2021-11-05 10:25 UTC
Using 1.0 on Linux using https://github.com/hexomancer/sioyek/releases/download/v0.31.119/sioyek-release-linux.zip

I have tried several epubs, they render perfectly, but when I click on the chapters or internal links they all just take you back to page 1.

**Comment by ahrm** [comment] 2021-11-05 10:37
Yes, epubs handle locations completely differently from PDFs (because they are reflowable they can't have fixed references to pages like PDFs). Adding that and reflowing requires some architectural changes to sioyek which I am willing to do but not in near future. Currently I am more focused on improving the core functionalities.
Anyway, I think this issue can be considered a duplicate of https://github.com/ahrm/sioyek/issues/5 so I will close it.

**Closed by ahrm** 2021-11-05 10:37 UTC
Labels: duplicate
