### ISSUE TITLE
[Feature request] goto_page_with_page_number can switch between physical page numbers and logical page number by config

### ISSUE THREAD

**Issue by temberature** [ahrm/sioyek#527] opened 2022-12-12 09:11 UTC
Currently, the sioyek goto_page_with_page_number command uses physical page numbers. It would be more convenient for many documents, particularly books, if this command used logical page numbers instead. 

It is hoped that a configuration setting will be made available to allow for this.

![WX20221212-170203](https://user-images.githubusercontent.com/3735863/207004403-f4160f00-f002-4fcd-8385-a14d20134bdd.png)
![WX20221212-170137](https://user-images.githubusercontent.com/3735863/207004415-306b8ceb-0d91-4419-871d-659ac5e39f33.png)

why is there two sets of page numbers? (Edit PDF)
https://answers.acrobatusers.com/why-sets-page-numbers-q42394.aspx

**Comment by ahrm** [comment] 2022-12-12 09:33
Duplicate of https://github.com/ahrm/sioyek/issues/527. MuPDF (the PDF engine that we use) doesn't have this feature so we won't have that until they add it. There is a patch that adds this to mupdf but I don't think it is worth complicating the build process.

**Comment by temberature** [comment] 2022-12-12 15:50
I discovered that sumatrapdf uses a suboptimal method to implement this after doing some research.

https://github.com/sumatrapdfreader/sumatrapdf/blob/06f1dc9b2bf08d45ab36820bd5b3a14c0db39241/src/Toolbar.cpp#L675

**Comment by ahrm** [comment] 2022-12-12 15:54
> @ahrm Do you mean following link:

Yes, like I said, it is possible to add it using a patch, but it is not worth complicating the build process. By the way I blame linux distributions for this problem. If they didn't insist on using the distributions' mupdf we could just patch our version of mupdf and be done with it. This is one more reason archlinux's way of handling packages is fucking idiotic. See this issue for more information https://github.com/ahrm/sioyek/issues/302.

**Comment by ahrm** [comment] 2022-12-12 15:55
> I discovered that sumatrapdf uses a suboptimal method to implement this after doing some research.

I don't think the part you linked has anything to do with this. Like I said there is a patch that adds this to mupdf but I don't think I will add it for reasons explained above.

**Comment by temberature** [comment] 2022-12-12 16:04
> > I discovered that sumatrapdf uses a suboptimal method to implement this after doing some research.
> 
> I don't think the part you linked has anything to do with this. Like I said there is a patch that adds this to mupdf but I don't think I will add it for reasons explained above.

I'm not sure about the exact code, but I do know that the function exists. 
I just provide this information for reference and my requirement for this is not very demanding.

**Comment by ahrm** [comment] 2023-04-16 11:59
It appears that mupdf 1.22 has added the page labels feature [1] so we probably can add it in the next release.

[1] https://github.com/ArtifexSoftware/mupdf/blob/master/CHANGES

**Comment by ahrm** [comment] 2024-01-26 10:20
We have added `goto_page_with_label` in development branch.

**Closed by ahrm** 2024-01-26 10:20 UTC
