### ISSUE TITLE
Recognise APA format citations?

### ISSUE THREAD

**Issue by faurehu** [ahrm/sioyek#232] opened 2022-05-19 06:18 UTC
I read papers where the text citations are in the form of `(Jablonkski 2014).`

Listed:
```
Jablonski, Ryan S. 2014. “How aid targets votes: the impact of electoral incentives on foreign aid distribution”World Politics 66 (2). 293-330. 
```

Would be nice if this was also recognised by sioyek.

**Comment by ahrm** [comment] 2022-05-19 07:46
Duplicate of https://github.com/ahrm/sioyek/issues/102.

**Closed by ahrm** 2022-05-19 07:46 UTC
Labels: duplicate
