### ISSUE TITLE
toggle_select_highlight: second highlight copies text from first one and then remove first one

### ISSUE THREAD

**Issue by raffaem** [ahrm/sioyek#777] opened 2023-07-26 09:19 UTC
I have 2 bugs with `toggle_select_highlight`:

1. When I switch to visual mode (`v`) the second time, it pastes the text of the first selection in top bar (the one that asks for the labels), instead of starting empty
2. Creating a second highlight removes the first one

Here is a video:
[20230726T104428.webm](https://github.com/ahrm/sioyek/assets/54762742/6cc522b1-eaaf-4eb7-b9e7-3ac1b3924289)

**Comment by ahrm** [comment] 2023-07-26 09:45
The bug here is that select highlight mode works only with mouse selection and doesn't work with keyboard-selection. While I did not do this intentionally, I don't think it is a big deal (actually I think it is a feature!), because the main purpose of select highlight mode was to make highlighting easier when using only mouse. If you are already using keyboard, it is pretty easy just to press h or use `add_highlight_with_current_type` command to highlight the selected text.

> When I switch to visual mode (v) the second time, it pastes the text of the first selection in top bar (the one that asks for the labels), instead of starting empty

This is intended. We automatically fill the textbar with selected text. This is useful for example to search a term by selecting it and pressing `/`. You can unselect text by pressing escape.

> Creating a second highlight removes the first one

The bug is that we are not even creating a highlight. What you see as highlighted is just the selected text, which should be removed when another text is selected.

**Comment by raffaem** [comment] 2023-07-26 12:26
ok, can we have a mode for the keyboard?

It is more convenient to select by just typing the labels.

I'm thinking about
1. Press the keybinding
2. Type first label
3. Type second label

It would automatically recognize whether you have finished typing the first label and wait for the second label, without the need to separate the two labels with space.

This would require to encode the labels in a way that makes clear whether there is another letter to follow or the label is fully specified already

Like UTF8 encoding works..

**Comment by ahrm** [comment] 2023-07-26 12:49
It is possible, but ... why? You have to press at least 4 buttons already, is pressing an extra space such a big deal?

**Comment by marty-oehme** [comment] 2023-10-02 11:38
I think I stumbled into the same issue in trying to set up the following workflow:

1. Press a single button (`V`) to enter keyboard selection.
1. Enter `first-label <space> second-label`.
1. Have the selected text instantly become highlighted (without additional button presses such as `h`).

I tried setting up a key binding doing

`toggle_select_highlight;keyboard_select V` which does not work I believe due to the mouse-only mode for `toggle_select_highlight` you mentioned above?

`keyboard_select;add_highlight_with_current_type V` seems to highlight *previously* highlighted text if there was any but not take into account (or wait for) a label selection to be made.

Is there a way to accomplish this simple key->label->label workflow for quick highlights that I am not seeing?

**Comment by ahrm** [comment] 2023-10-02 11:53
The issue is that in the current version of sioyek commands like `keyboard_select` execute immediately. So when you run `keyboard_select;add_highlight_with_current_type`, we run `add_highlight_with_current_type` the moment you press `V` which is not what you want.

I have already fixed this issue but the code is not yet public. It will be released with the next version of sioyek.

**Comment by marty-oehme** [comment] 2023-10-02 12:52
Perfect, that is good to know! Will simply wait for the new version.

Thanks for the quick response and the amazing software.

**Comment by ahrm** [comment] 2024-01-21 15:58
This is fixed in the development branch of this repo.

**Closed by ahrm** 2024-01-21 15:58 UTC
