### ISSUE TITLE
Two-page/ultrawide view

### ISSUE THREAD

**Issue by DOFfactory** [ahrm/sioyek#101] opened 2021-11-10 09:43 UTC
Absolutely love the software, please keep up the good work!

I was wondering whether a two-page view could be introduced, as some of us have an ultrawide monitor, and it would enhance readability across pages...

**Comment by ahrm** [comment] 2021-11-10 10:19
Duplicate of https://github.com/ahrm/sioyek/issues/64 . As I explained there, it is unlikely that this feature will be added to sioyek anytime soon. I will add it only if I can find a clean way to implement it without complicating the code too much.

**Comment by DOFfactory** [comment] 2021-11-10 11:06
Ah, I see. It is weird, as I have to zoom out the text quite considerably, with 2/3 of the screen white (makes it hard to read). Also, the window size in Win10 is not really possible to change or move, so I cannot give it a portion of the screen and use other parts for something else. At least make the window then resizeable please, that would help a lot!

**Comment by ahrm** [comment] 2021-11-10 12:13
> Ah, I see. It is weird, as I have to zoom out the text quite considerably, with 2/3 of the screen white (makes it hard to read). Also, the window size in Win10 is not really possible to change or move, so I cannot give it a portion of the screen and use other parts for something else. At least make the window then resizeable please, that would help a lot!

The window should be resizable and movable. Is it not working for you?

**Comment by DOFfactory** [comment] 2021-11-10 12:22
No, I cannot change the size for some reason. Also, if I hit alt+space the resize option is not enabled:

![image](https://user-images.githubusercontent.com/10846169/141112323-917fba9a-2120-4099-9d93-a72f3915a0d5.png)

**Comment by ahrm** [comment] 2021-11-10 14:03
> No, I cannot change the size for some reason. Also, if I hit alt+space the resize option is not enabled:
> 
> ![image](https://user-images.githubusercontent.com/10846169/141112323-917fba9a-2120-4099-9d93-a72f3915a0d5.png)

Well, in this picture the window is maximized. First you need to minimize the window and then you can resize it.

**Comment by DOFfactory** [comment] 2021-11-10 14:14
Ah, I see, sorry, got confused also with the fullscreen option. When I clicked on the Restore button (!) on the right, nothing changed, the window remained maximized. However, when I clicked on the Restore option in the menu (on the left), the window changed accordingly. Maybe something weird is happening with the button? In any case, now it works, I can resize the window.

**Comment by ahrm** [comment] 2022-08-04 15:39
Note that while we probably will not natively support two-page view. It can easily be replicated using scripts. I added a simple script to create a dual panel version of current document here:
https://github.com/ahrm/sioyek/blob/main/scripts/dual_panelify.py

Here is how it looks:

https://user-images.githubusercontent.com/6392321/182888181-e48cf3d3-7b6a-4fe1-b632-03b4c019f921.mp4

Note that the settings described in the python file probably won't work with 1.4 release version of sioyek and require new commits (this script can still be used in old versions of sioyek using the old `execute_command_*` style configs and `%1` instead of `%{file_path}`).

**Closed** 2022-12-06 11:59 UTC

**Comment by ahrm** [comment] 2023-04-11 19:32
That's just an unimportant warning not an error (there are some other possible arguments that are missing). I don't know what the issue may be but it is something else (you could try pasting the command into a command line (after replacing `%` variables with the correct values ) and see if there are any errors).

**Comment by SuperContraptionGuy** [comment] 2024-04-24 19:29
Is there any way to change whether the odd or even pages are to the left? Some pdfs have a cover page that offsets the dual view by one page, putting the pages on the 'wrong' side compared to the printed version.
Examples

preferred:
![correct](https://github.com/ahrm/sioyek/assets/9522981/9679a213-93a0-4405-96de-d928c6bbacbe)

vs flipped:
![swapped](https://github.com/ahrm/sioyek/assets/9522981/ab4cc7c9-2b41-473e-800d-6b4dc633189d)

**Comment by joihn** [comment] 2024-10-14 09:11
I installed dual_panelify on latest sihoyek development branch
shortcut had to be modified to 
`new_command _dual_panelify python /home/maxime/Documents/code/sioyek/scripts/dual_panelify.py %{sioyek_path} %{file_path}`

it works, but there is a weird margin on the left, and the the on the right is cropped :cry:

**Comment by ahrm** [comment] 2024-10-14 09:13
In the development branch we have a built-in `toggle_two_page_mode` command, there is no need for extensions anymore.

**Comment by quantumfrost00** [comment] 2024-10-19 06:30
@ahrm How can I access and implement the development branch ? Can you guide me ?

**Comment by ahrm** [comment] 2024-10-19 06:37
The development branch is here: https://github.com/ahrm/sioyek/tree/development, there are also experimental preview builds available in the release page. Compiling it is the same as the main branch except instead of Qt 5.* you should use qt 6.7+.

**Comment by quantumfrost00** [comment] 2024-10-19 07:13
Thankyou so much. It helps a lot. The two page preview mode is really awesome.

**Comment by NailGit** [comment] 2024-12-01 17:27
> The development branch is here: https://github.com/ahrm/sioyek/tree/development, there are also experimental preview builds available in the release page. Compiling it is the same as the main branch except instead of Qt 5.* you should use qt 6.7+.

I have compiled but there is no two page mode. The two page regime is really useful mode for this excellent project.

**Comment by joihn** [comment] 2024-12-02 09:13
I have recently compiled develop, and I do have the feature,
try inputing `:` (will open search panel ) `toggle_two_page_mode`

**Comment by NailGit** [comment] 2024-12-03 00:03
> I have recently compiled develop, and I do have the feature, try inputing `:` (will open search panel ) `toggle_two_page_mode`

I compiled the main branch. I try to compile development branch but it needs to QT6.5+, but in my system there is QT5 only. I installed QT6.5 but still the compilation uses QT5. I do not understand why.  For installation of the QT6.5 I used [this guide](https://www.youtube.com/watch?v=43Cel0Fz3x0). qmqke6 appears but compilation stll use QT5.

**Comment by KorigamiK** [comment] 2025-05-22 05:59
> > I have recently compiled develop, and I do have the feature, try inputing `:` (will open search panel ) `toggle_two_page_mode`
> 
> I compiled the main branch. I try to compile development branch but it needs to QT6.5+, but in my system there is QT5 only. I installed QT6.5 but still the compilation uses QT5. I do not understand why. For installation of the QT6.5 I used [this guide](https://www.youtube.com/watch?v=43Cel0Fz3x0). qmqke6 appears but compilation stll use QT5.

Hi, were you able to solve this issue?
If not you can now use CMake as the build system to automatically use correct qt version you have installed.

**Comment by NailGit** [comment] 2025-09-15 22:25
> > > I have recently compiled develop, and I do have the feature, try inputing `:` (will open search panel ) `toggle_two_page_mode`
> > 
> > 
> > I compiled the main branch. I try to compile development branch but it needs to QT6.5+, but in my system there is QT5 only. I installed QT6.5 but still the compilation uses QT5. I do not understand why. For installation of the QT6.5 I used [this guide](https://www.youtube.com/watch?v=43Cel0Fz3x0). qmqke6 appears but compilation stll use QT5.
> 
> Hi, were you able to solve this issue? If not you can now use CMake as the build system to automatically use correct qt version you have installed.

I just found new release here https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0 . Two page function works fine. Thanks a lot.  But one problem - the scroll bar does not work.
