### ISSUE TITLE
Smart jump to bibliographic item does not work with specific reference format?

### ISSUE THREAD

**Issue by toolleeo** [ahrm/sioyek#274] opened 2022-06-12 14:47 UTC
The smart jump, which works fine for many documents, seems not to work in a document with the following format of the bibliography:

![image](https://user-images.githubusercontent.com/22637622/173238792-f2318eb3-baa0-481f-88cd-674e3816ea9a.png)

The citation has instead a "standard" format:

![image](https://user-images.githubusercontent.com/22637622/173238963-b3f8b855-2b38-45f7-8157-3ef40b5abe13.png)

**Comment by ahrm** [comment] 2022-06-12 15:00
Duplicate of https://github.com/ahrm/sioyek/issues/102.

**Closed by ahrm** 2022-06-12 15:00 UTC
