### ISSUE TITLE
support double page display 

### ISSUE THREAD

**Issue by zerone0x** [ahrm/sioyek#705] opened 2023-04-24 15:45 UTC

**Comment by zerone0x** [comment] 2023-04-25 15:23
Regarding the reading mode, I believe that a two-page display would be appropriate for larger screens. It would be excellent if this feature could be included in the configuration settings. 
An example in the below pic
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/39543393/234325336-ebd8c8ff-5d61-4b7b-85b8-12d9974b8a24.png">

**Comment by marty-oehme** [comment] 2023-10-02 11:15
This is probably a duplicate of #64. 

While I agree it would be lovely to have baked in as a first-class feature, for the time being something kinda sorta working can be hacked up with this: https://github.com/ahrm/sioyek/issues/101#issuecomment-1205425704 suggestion.

**Comment by zerone0x** [comment] 2023-10-07 15:07
> This is probably a duplicate of #64.
> 
> While I agree it would be lovely to have baked in as a first-class feature, for the time being something kinda sorta working can be hacked up with this: [#101 (comment)](https://github.com/ahrm/sioyek/issues/101#issuecomment-1205425704) suggestion.

Thanks for your information! I will try to use the script.

**Comment by ahrm** [comment] 2024-02-04 15:42
Added two page mode in the development branch (`toggle_two_page_mode` command).

**Closed by ahrm** 2024-02-04 15:42 UTC

**Comment by douglas-c-lobo-alb** [comment] 2026-03-11 10:18
it is complete? how so I activate it inside the app?

**Comment by marty-oehme** [comment] 2026-03-11 11:00
If you are running the development version you can activate it like any other [command](https://sioyek-documentation.readthedocs.io/en/latest/commands.html) in sioyek, using `:toggle_two_page_mode` - or you bind it to a key. I have it simply set to be toggled with `d` by adding the following to `keys_user.config`:

```ini
toggle_two_page_mode d
```

If you are running the latest release version (2.0.0) from 2022, this change is not yet available. If you want to stay on official release versions you will have to wait for the next release to use the built-in double paged mode.

**Comment by douglas-c-lobo-alb** [comment] 2026-03-11 14:46
> If you are running the latest release version (2.0.0) from 2022, this change is not yet available. If you want to stay on official release versions you will have to wait for the next release to use the built-in double paged mode.

That was my doubt, if it was already released. Thanks, I'll try to build a newer development version.
