### ISSUE TITLE
[Dev][REGRESSION?] Config locations no longer set automatically

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#920] opened 2024-01-16 16:52 UTC
I've noticed that on the development branch, there's a new bug affecting me: The application is no longer utilizing the standard configuration directories. (I.e., `~/Library/Application Support/sioyek`) Instead, we have to copy our configuration files directly into the application directory (`/Applications/sioyek.app/Contents/MacOS/`). Moreover, the database is being saved in that location as well, which unfortunately means it gets deleted every time we do a rebuild.

Is this expected behavior?

**Comment by ahrm** [comment] 2024-01-16 17:00
I don't think it is intended behavior but I don't have a mac machine so I can't test it right now.

**Comment by NightMachinery** [comment] 2024-01-17 12:03
I can debug it. Where are some places in the code I should check?

**Comment by ahrm** [comment] 2024-01-17 12:32
The paths are handled in the `configure_paths` function in `main.cpp`.

**Comment by ahrm** [comment] 2024-02-25 08:59
This should be fixed in https://github.com/ahrm/sioyek/commit/2d8487a479f7485ae4c77612173add917f8f0264.

**Closed** 2024-03-07 08:41 UTC
