### ISSUE TITLE
[Bug] Segmentation fault in typing mode 

### ISSUE THREAD

**Issue by HakonHarnes** [ahrm/sioyek#545] opened 2022-12-22 01:06 UTC
**Steps to reproduce:** 
1. Toggle typing mode. 
2. Enter inctorrect character. 
3. Press backspace twice. 

This results in the following error: 
```'sioyek $argv' terminated by signal SIGSEGV (Address boundary error)```

**Comment by ahrm** [comment] 2022-12-22 14:19
Can't reproduce the issue. Does this happen in a specific document/location?

**Comment by HakonHarnes** [comment] 2022-12-22 14:57
I'm not able to reproduce on Windows. The issue occured on arch linux running i3wm. I'll do some experimenting when I get back to my linux computer.

**Comment by HakonHarnes** [comment] 2022-12-23 01:26
I've done some testing. Here's what I've observed: 

- The bug is not present on Windows, only on Linux.
- It is document and location independent.
- It does not occur on double backspace as I mistakenly stated earlier. It happens after a single backspace (it takes about ~1 second before it crashes)

**Comment by ahrm** [comment] 2023-01-01 11:26
Should be fixed in 0dfc8d6d557c725a97441f8291cda37191578ac5.

**Comment by ahrm** [comment] 2023-01-01 12:25
Okay it was not completely fixed but it should be actually fixed in c0c4f5c1e6b01eda075271591fcb81c41fead6eb.

**Closed** 2023-01-10 09:41 UTC
