### ISSUE TITLE
[Bug] Huge memory leak when zooming, helper window and reader screen

### ISSUE THREAD

**Issue by windowswithoutborders** [ahrm/sioyek#568] opened 2022-12-27 03:19 UTC
OS: macOS 13.1 22C65 arm64
Host: MacBook Air (M2, 2022)
Sioyek Version: sioyek 2.0.0

On my macOS system while reading a PDF document, creating a portal and adjusting the zoom level within the helper window will cause Sioyek  to consume excessive amounts of memory until it crashes. 

If it is of any use, here is a bit of log output after crashing:

```
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
[1]    1799 terminated  /Applications/sioyek.app/Contents/MacOS/sioyek
```
<img width="539" alt="Screenshot 2022-12-26 at 6 37 44 PM" src="https://user-images.githubusercontent.com/67998787/209604038-2eea0245-1605-4838-b2ed-297bd7702391.png">

Additionally, a similar effect can be achieved wherein Sioyek will consume a large amount of memory by rapidly zooming in and out of the reader screen alone with CMD+Scroll Wheel. Sioyek does not crash this time as it is able to release the memory once the "zoom abuse" has stopped.

**Comment by ahrm** [comment] 2022-12-27 11:04
This was not a memory leak. We don't immediately release the rendered pages in case we need them again, but after a bit of not using them, they are released automatically, so this part is by design.

However, the problem was that we didn't limit how much you could zoom in the helper window, so you could zoom in so much that even rendering a single page would require enormous amounts of memory, which would crash sioyek. It should be fixed in e0d0cef140262595ef2895992d39fbad0fd51f1c, now we don't allow you to zoom in too much in the helper window.

**Closed** 2022-12-29 11:42 UTC
