### ISSUE TITLE
Bug when setting marks in different documents

### ISSUE THREAD

**Issue by aluminum1** [ahrm/sioyek#662] opened 2023-03-16 05:37 UTC
Suppose I have two documents X and Y. I set a mark at position A and then also at position B in document X.  Then, I navigate to document Y. From document Y, I type in `B to attempt to go back to mark B in document X. But it just goes back to mark A.

**Comment by ahrm** [comment] 2023-03-16 09:21
I can't reproduce the issue. Can you explain more thoroughly? For example what names do you use for the symbols? How do you open multiple documents (in multiple windows or on a single window?).

**Comment by aluminum1** [comment] 2023-03-17 07:20
Thank you for your response. I can say it more precisely now. Firstly, everything is happening on a single window. I cannot set more than one "capital letter" marks in a single document. And, if I remember correctly, if you want to be able to switch between marks in different documents, then they need to be capital letters. So, I am unable to have two marks "A" and "B" in document X, and another mark "C" in document Y. This restriction is possibly built into the design of Sioyek. But it is a use case which comes up a lot for me at least.

**Comment by ahrm** [comment] 2023-03-17 18:36
It should be fixed in 890a1042b11fff73ae10576ee025e2a61fc822df.

Explanation of the bug:
I got c++'d. Apparently `{}` can be converted to bool and caused c++ to call an incorrect overload of the document opening function.

**Comment by aluminum1** [comment] 2023-03-17 19:53
Brilliant thank you!

**Closed** 2023-03-19 08:51 UTC
