### ISSUE TITLE
AppImage fails on Debian 10

### ISSUE THREAD

**Issue by Symbian9** [ahrm/sioyek#10] opened 2021-07-28 20:21 UTC
- OS: Debian 10.x buster
- Version:  `v0.31.5`
  - https://github.com/ahrm/sioyek/releases/download/v0.31.5/sioyek-release-linux-portable.zip
  - https://github.com/ahrm/sioyek/releases/download/v0.31.5/sioyek-release-linux.zip

### Actual behavior

Seems like both AppImages created on Linux distro which has more recent version of `libstdc` than actual LTS release

```
$ ./Sioyek-x86_64.AppImage
./Sioyek-x86_64.AppImage: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./Sioyek-x86_64.AppImage)
```

### Expected behavior

It should run without issues on Linux LTS distributions, so if possible use build environment which would allow use AppImage on LTS releases of both Ubuntu and Debian.

### References

- https://stackoverflow.com/questions/52663287/glibcxx-3-4-26-not-found
- https://stackoverflow.com/questions/63190229/glibcxx-3-4-26-not-found-running-cross-complied-program-on-beaglebone

**Comment by ahrm** [comment] 2021-07-29 07:37
Yes. I do use g+=-9 because I use some of the c++17 features. I'll see if I can get it to compile without c++17.

**Comment by David-Else** [comment] 2021-07-30 09:15
I just found this awesome application, please can you make sure it works on RHEL/Rocky/Centos 8? I hope this info lets you know what is needed, but I can provide any more info you need:
```
$ldd --version
ldd (GNU libc) 2.28

$gcc --version
gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)

Installed Packages:
Name         : libstdc++
Version      : 8.4.1

Available Packages:
Name         : gcc-toolset-10-libstdc++-devel
Version      : 10.2.1
```
Thanks!

**Comment by ahrm** [comment] 2021-08-02 10:47
I think this is fixed in 9bffce39641d6c24dd061489b1de64e92d94e5c8 . Here is an experimental build of the latest commit (there may be bugs still, specially regarding paths in linux):

https://github.com/hexomancer/sioyek/releases/download/v0.31.64/sioyek-release-linux-portable.zip

I tested it in a vanilla debian VM and it works.

**Closed by ahrm** 2021-08-02 10:47 UTC

**Comment by hbt** [comment] 2021-08-02 10:50
@ahrm Confirmed to work. Great work packaging it.

**Comment by Symbian9** [comment] 2021-08-02 21:18
It launched & shows number of autoloaded `tutorial.pdf`, but document is not rendered:

```
$ ./Sioyek*.AppImage
Setting $XDG_CONFIG_HOME to /home/user/AppImages/Sioyek-x86_64.AppImage.config
default_config_path: /tmp/.mount_SioyekktARbR/usr/bin/prefs.config
default_keys_path: /tmp/.mount_SioyekktARbR/usr/bin/keys.config
user_config_path: /home/user/AppImages/Sioyek-x86_64.AppImage.config/.local/share/Sioyek/prefs_user.config
user_keys_path: /home/user/AppImages/Sioyek-x86_64.AppImage.config/.local/share/Sioyek/keys_user.config
database_file_path: /home/user/AppImages/Sioyek-x86_64.AppImage.config/.local/share/Sioyek/test.db
tutorial_path: /home/user/AppImages/Sioyek-x86_64.AppImage.config/.local/share/Sioyek/tutorial.pdf
last_opened_file_address_path/home/user/AppImages/Sioyek-x86_64.AppImage.config/.local/share/Sioyek/last_document_path.txt
shader_path/tmp/.mount_SioyekktARbR/usr/bin/shaders
config file change listener constructor called1starting index thread ...
Figure 1: Mandlebrot Set
figure indexing finished ... 
warning! calling open() on an open document
texture: 3
texture: 4
texture: 5
texture: 6
texture: 8
getting links .... for 0
texture: 9
deleting cached texture ... 
deleting cached texture ... 
deleting cached texture ... 
deleting cached texture ... 
deleting cached texture ... 
deleting cached texture ... 
texture: 10
deleting cached texture ... 
Empty filename passed to function
starting index thread ...
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1432, resource id: 19502986, major code: 40 (TranslateCoords), minor code: 0
getting links .... for 0
figure indexing finished ... 
texture: 11
deleting cached texture
```

![pic](https://imgur.com/hPMQMqL.png)

**Comment by ahrm** [comment] 2021-08-03 06:57
What is your OpenGL version?

```
glxinfo | grep version
```

**Comment by hbt** [comment] 2021-08-03 11:25
@Symbian9 I'm on Debian too and https://github.com/hexomancer/sioyek/releases/download/v0.31.64/sioyek-release-linux-portable.zip **works** for me. 


glx info 

```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.6.0 NVIDIA 440.82
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL version string: 4.6.0 NVIDIA 440.82
OpenGL shading language version string: 4.60 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 440.82
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_group_vote, GL_EXT_shader_implicit_conversions, 
```

**Comment by Symbian9** [comment] 2021-08-03 12:06
Here is my:

```
$ glxinfo
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL vendor string: X.Org R300 Project
OpenGL renderer string: ATI RS600
OpenGL version string: 2.1 Mesa 18.3.6
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```

**Comment by ahrm** [comment] 2021-08-03 12:20
> @ahrm, Here is my `glxinfo`:
> 
> ```
> $ glxinfo | grep version
> server glx version string: 1.4
> client glx version string: 1.4
> GLX version: 1.4
>     Max core profile version: 0.0
>     Max compat profile version: 2.1
>     Max GLES1 profile version: 1.1
>     Max GLES[23] profile version: 2.0
> OpenGL version string: 2.1 Mesa 18.3.6
> OpenGL shading language version string: 1.20
> OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.3.6
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
> ```

Yeah. Your OpenGL version is too low. We require at least version 3.3 . I recommend updating your graphics driver.

**Comment by ahrm** [comment] 2021-11-04 07:16
> On Centos 8.4 and sioyek 1.0 I am getting:
> 
> ```
> Sioyek-x86_64.AppImage: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by Sioyek-x86_64.AppImage)
> ```
> 
> Centos has `glibc 2.28`.
> 
> I saw in [#5 (comment)](https://github.com/ahrm/sioyek/issues/5#issuecomment-885432677) that this software supports epub but not reflowing... does that work now? Thanks!

It is strange since this is the exact same error which should be fixed. I will look into it when I have the time to create a centos virtual machine.

No there is still no reflowing.

**Comment by David-Else** [comment] 2021-11-04 08:45
OK, how strange this is happening when it is meant to be fixed. I actually recommend Rocky Linux, it is identical to Centos and RHEL. Here is some more info in case it helps:
```
glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.3.3
OpenGL core profile shading language version string: 4.60
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.3.3
OpenGL shading language version string: 4.60
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.3.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix, 
```

**Comment by ahrm** [comment] 2021-11-04 10:25
> OK, how strange this is happening when it is meant to be fixed. I actually recommend Rocky Linux, it is identical to Centos and RHEL. Here is some more info in case it helps:
> 
> ```
> glxinfo | grep version
> server glx version string: 1.4
> client glx version string: 1.4
> GLX version: 1.4
>     Max core profile version: 4.6
>     Max compat profile version: 4.6
>     Max GLES1 profile version: 1.1
>     Max GLES[23] profile version: 3.2
> OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.3.3
> OpenGL core profile shading language version string: 4.60
> OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.3.3
> OpenGL shading language version string: 4.60
> OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.3.3
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
>     GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix, 
> ```

I built `sioyek` using an older gcc version which should work on your machine. Does this work for you:
Portable version: https://github.com/hexomancer/sioyek/releases/download/v0.31.119/sioyek-release-linux-portable.zip
Normal version: https://github.com/hexomancer/sioyek/releases/download/v0.31.119/sioyek-release-linux.zip

**Comment by David-Else** [comment] 2021-11-04 11:31
@ahrm This version works, thanks! It renders epub MUCH better and faster than Okular too, nice work!

Is it possible to use this version of gcc in all releases, or will that make things too crusty for people on newer distros?

**Comment by ahrm** [comment] 2021-11-04 11:43
> @ahrm This version works, thanks! It renders epub MUCH better and faster than Okular too, nice work!
> 
> Is it possible to use this version of gcc in all releases, or will that make things too crusty for people on newer distros?

Nice. Though I have nothing to do with fast rendering, you should thank MuPDF devs for that :D .
It is probably possible to use this version for all releases. I have to do more testing though.

**Comment by Endle** [comment] 2021-11-04 12:48
> Nice. Though I have nothing to do with fast rendering, you should thank MuPDF devs for that :D .

Okular uses Poppler as backend (as Wikipedia says), which seems to be slower than MuPDF.  Fou have chosen a good backend :)

> It is probably possible to use this version for all releases. I have to do more testing though.
We can start from changing GitHub Action at https://github.com/ahrm/sioyek/blob/main/.github/workflows/build_and_release.yml#L107
(Or use github action as the final step verification).

Do you think it can bring some benefits if we try different gcc versions with a build matrix? I can make a PR for that which should not be hard
