### ISSUE TITLE
Sioyek crashes on command user input

### ISSUE THREAD

**Issue by ejuarezg** [ahrm/sioyek#342] opened 2022-07-29 01:03 UTC
Hi! I was trying out the new script features showcased in your [blog post](https://ahrm.github.io/jekyll/update/2022/07/05/implementing-a-screen-reader-for-sioyek.html) However, I'm finding that scripts that use "%5" crash before I can enter any text. I was able to reproduce this behavior on two different machines (Pop OS 22.04 and Manjaro). The shell script I'm using to figure out what's wrong contains the following:

```
#!/bin/sh

touch "/home/user/$1.txt"
```

The corresponding sioyek config in `prefs_user.config` is `execute_command_c /home/user/test.sh "%5"`

**Comment by ahrm** [comment] 2022-07-29 09:59
I could not reproduce this issue on an ubuntu 21.04 laptop. Which commit are you compiling (we had an issue with text inputs in commands a while ago, but it should be fixed in the latest commits). Also what compiler are you using to compile sioyek?

Also does the issue still happen with the latest experimental builds here?
https://github.com/hexomancer/sioyek/releases/tag/v0.31.356

**Comment by ejuarezg** [comment] 2022-07-29 16:22
The experimental build solved the problem! I was using the v1.4.0 AppImage before.

**Closed** 2022-07-29 18:54 UTC
