### ISSUE TITLE
Cannot launch multiple instances in MacOS

### ISSUE THREAD

**Issue by faurehu** [ahrm/sioyek#429] opened 2022-09-21 20:29 UTC
I have tried using the `should_launch_new_window` and `should_launch_new_instance` flags in pref_user.config and I can't launch a second instance.

I have also tried to disable the `toggle_one_window` setting, also without success.

I wonder if there's something that I'm doing wrong or whether this feature is not generally available for MacOS computers.

**Comment by ahrm** [comment] 2022-09-21 21:05
Does the `new_window` command work?

**Comment by faurehu** [comment] 2022-09-21 21:08
No, I cannot find it when I press `:`, nor anything happens when I press `:new_window<RET>`.

I also tried binding the command to a hotkey in my `keys_user.config` to with no success.

**Comment by ahrm** [comment] 2022-09-21 21:11
That's strange. I will try to see if I can reproduce this problem if I get my hands on a mac (probably will be a while, in the meantime, if anybody else can reproduce the problem please share it here).

**Comment by faurehu** [comment] 2022-09-21 21:17
Ok. You might want to start labelling all Mac issues so it's easier to know what you should try to reproduce once you have a Mac.

Thank you for your help and for the app too!

**Comment by undefdev** [comment] 2022-09-21 22:25
FYI, for me opening a new window per default doesn't seem to work either (I'm using `should_launch_new_window	1`). But `new_window` works fine. I installed via the homebrew cask.

**Comment by ahrm** [comment] 2022-09-21 23:20
There was a bug with `should_launch_new_window` which should be fixed in the latest commits. See this issue: https://github.com/ahrm/sioyek/issues/424.

**Comment by albert-ying** [comment] 2022-09-26 02:55
`should_launch_new_window` works for me on MacOS, but start from the second window, the `startup_commands` seems been ignored.
I have `startup_commands    toggle_custom_color`, but the new windows always start with white background

**Comment by ahrm** [comment] 2022-09-26 08:25
Which sioyek build are you using. This is a bug in version 1.5, but it should be fixed now (not released in a stable build yet though).

**Comment by faurehu** [comment] 2022-10-12 20:11
I installed the newest version and now it works. Thank you.

**Closed** 2022-10-13 09:56 UTC
Labels: help wanted
