### ISSUE TITLE
Keyboard text selection with `v` and searching with `/` bring  current selected text into input box.

### ISSUE THREAD

**Issue by unifreak** [ahrm/sioyek#892] opened 2023-12-25 05:58 UTC
I'm on archlinux with Linux version 6.6.2, using sioyek 2.0.0.

The problem is:

1. select some text with `v`.
2. now press `v` again, trying for new text selection.
3. sioyek will bring the previously selected text into the "Labels" input box. So I need to clear the text first, then input the new labels for new text selection.

The same thing also happen when pressing `/` for search: old selected text will be brought into the search box.

I'm expecting that everytime I press `v` or `/`, there should be empty input box for fresh new text selection or searching.

**Comment by ahrm** [comment] 2023-12-25 08:12
This is by design. For example it is useful when you want to find some other instances of selected text in the document. If you don't want that you can press escape to clear the selected text prior to pressing `/`.

**Comment by unifreak** [comment] 2023-12-27 02:23
The design only make sense in the workflow `v` then immediately `/`, and I find myself seldom do  that: I'm either doing a sequence of `/` (when noting down things), or the searching words has nothing to do with the previous `v`. But that's just me.

It helps if there is a config option to disable the default behavior. But the `escape` trick is convenient enough, too. 

(Love sioyek, thanks!)

**Comment by ahrm** [comment] 2024-01-19 12:34
Added a `fill_textbar_with_selected_text` config option in this commit in development branch: https://github.com/ahrm/sioyek/commit/e3b09302dced2afedef47e174df0b3593b61f709.

**Comment by NightMachinery** [comment] 2024-01-20 12:43
@ahrm Why fill the text box for `v` (`keyboard_select`) though? Does it ever make sense for that? I thought `v` only works with `label1 label2<enter>`.

**Comment by ahrm** [comment] 2024-01-20 13:04
Currently we fill the textbox for all text-based commands, so we can't distinguish `keyboard_select`.

**Comment by ahrm** [comment] 2024-01-20 15:47
> @ahrm Why fill the text box for `v` (`keyboard_select`) though? Does it ever make sense for that? I thought `v` only works with `label1 label2<enter>`.

This should be fixed in https://github.com/ahrm/sioyek/commit/cc2e775aa8a1d8b92575bc9abab5033b574c66ad .

**Closed** 2024-01-23 08:23 UTC

**Comment by NightMachinery** [comment] 2024-01-23 09:17
@ahrm 
1. The text that is automatically entered is not selected, thus starting to type sth new will not overwrite it.
2. It seems to also fill the text bar from the clipboard?

**Comment by ahrm** [comment] 2024-01-23 09:21
> 1. The text that is automatically entered is not selected, thus starting to type sth new will not overwrite it.

I did not understand what you mean here. Please elaborate.

> 2. It seems to also fill the text bar from the clipboard?

Do you mean that we fill the textbar with clipboard? If so no we should not be doing that.

**Comment by NightMachinery** [comment] 2024-01-23 11:48
> I did not understand what you mean here. Please elaborate.

Ideally, when the text bar is filled with some text, this text should be "selected", as if one had pressed "ctrl+a" (select all). This way, if one presses enter, the automatic suggestion is accepted, but if one starts to type, the suggestion is discarded without affecting whatever is being typed.

> Do you mean that we fill the textbar with clipboard? If so no we should not be doing that.
Yes, it seemed so. I have disabled the option, so I am not sure. I'll report if I should confirm the bug, for now let's just ignore it.

**Comment by ahrm** [comment] 2024-01-23 12:01
Added in https://github.com/ahrm/sioyek/commit/caeba3e429913ca2d245da6a40cf86e80f9d4aa7.
